name: .NET Core Publish

on:
  push:
    branches:
      - main # Change this to your target branch

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.x' # Change this to the desired .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the application
      run: dotnet build --configuration Release

    - name: Publish the application
      run: dotnet publish -c Release -o publish
      
    - name: Change base-tag in index.html from / to BlazorGitHubPagesDemo
      run: sed -i 's/<base href="\/" \/>/<base href="\/BlackRose\/" \/>/g' release/wwwroot/index.html
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: published-app
        path: ./publish
